### ISSUE TITLE
Milestone 1 - Generate Link that Opens New File in Github Repo

### ISSUE THREAD

**Issue by coolaj86** [BeyondCodeBootcamp/Bliss#1]
Thoughtboard at https://www.figma.com/file/D1ZnwJ6xa8q3Q4by373Qhp/Bliss?node-id=0%3A1

- [x] A domain (temporarily bliss.coolaj86.com)
- [x] Form with Title, Date, Content
- [x] Slugify Title for filename & url slug
- [x] Format Dates
  - [x] ½
- [x] ability to COPY rather than a link (until Gitea supports query params)
- [x] Create on Github with query params
   - Re: https://github.com/isaacs/github/issues/1527#issuecomment-617466083

Supported Platforms:
- [x] GitHub
- [x] Gitea (v1.16+)
- [ ] GitLab (see https://gitlab.com/gitlab-org/gitlab/-/issues/337038)

**Comment by coolaj86** [comment]
Published in 388b7ec as v0.3.1
