### ISSUE TITLE
Milestone 1b - support multiple blog systems

### ISSUE THREAD

**Issue by coolaj86** [BeyondCodeBootcamp/Bliss#5]
- [x] Select different YAML frontmatter formatting based on blog system
   - [x] Desi
   - [x] Eon - https://git.rootprojects.org/root/therootcompany.com
      ```md
      ---
      title: 'Change Me To An Attractive Title'
      date: 2020-08-12T15:20:49-06:00
      updated: 2020-08-15T6:37:13-06:00
      youtube: ??? (ask Ryan)
      categories:
        - Security
      ---
      
      Hello.
      Is it me you're looking for?
      ```
   - [x] BashBlog (no frontmatter, just `# Title`)
      ```md
      # Hello

      Is it me you're looking for?
      ```
- [ ] Manual YAML editing? **Wait and see...**
   - syntax checking (parser library that's lightweight & works in browser)
